name: 'LYMG'

on:
  workflow_dispatch:
  push:
    branches:
     - main
  schedule:
    - cron: '*/30 * * * *'

jobs:

  check-in:
    runs-on: ubuntu-latest
    timeout-minutes: 30         
    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: test
      env:
        LYMG: ${{secrets.LYMG}}
      run: |
        python3 warp.py 
        
    - name: Delete releases and workflows runs
      uses: ophub/delete-releases-workflows@main
      with:
        delete_releases: false
        releases_keep_latest: 0
        delete_workflows: true
        workflows_keep_day: 0
        gh_token: ${{ secrets.GH_TOKEN }}
