name: 'LYMG'

on:
  workflow_dispatch:
  push:
    branches:
     - main
  schedule:
    - cron: '*/10 * * * *'

jobs:

  check-in:
    runs-on: ubuntu-latest
    timeout-minutes: 30         
    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: test
      env:
        LYMG: ${{secrets.LYMG}}
      run: |
        python3 warp.py 

